# attendance_router.py
PRESENT_START = "9:00"
PRESENT_END = "10:00"
LATE_END = "12:00"

# attendance_crud.py
START_DAY = 18
END_DAY = 0

LATE_FINE = 2000
ABSENT_FINE = 5000

# schedules_router.py
SCHEDULE_REGISTRATION_START_HOUR = "09:00"
SCHEDULE_REGISTRATION_CUTOFF_HOUR = "18:00"

# schedulers.py
MYSQLDUMP = "."